# Use Node.js version 20.12.1 as the parent image
FROM node:20.12.1

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json (if available)
COPY package*.json ./

# Install app dependencies
RUN npm install

# Bundle app source inside the Docker image
COPY . .

# Expose the port the app runs on
EXPOSE "${PORT}"

# Define environment variable for Node.js
ENV NODE_ENV="${NODE_ENV}"

# Run database migrations and start the app
CMD ["sh", "-c", "\
  if [ \"$NODE_ENV\" = \"production\" ]; \
  then \
  npm run create-tables && npm run migrate-database && npm run register && npm start; \
  else \
  npm run create-tables && npm run migrate-database && npm run register && npm run dev; \
  fi"]
