name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd bot/trainerdex/
            git pull origin main
            docker-compose -f docker-compose.yml -f docker-compose.prod.yml build
            docker-compose down
            docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
            # Wait for the container to fully start up
            sleep 10
            # and 'your_container_command' with the command you want to run inside your container
            docker exec trainerdex_app npm run register
